name: core
environment:
    sdk: '>=1.0.0 <2.0.0'
dependencies:
    data:
        git:
            url: git://github.com/elos/dart-data.git
            ref: master
dev_dependencies:
    test: '>=0.12.0 <0.13.0'
    test_runner: '<=0.2.16'
